apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ashishpandey1991/clock:latest    # Include tag for clarity
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        # -----------------------------------------------------------------
        # HEALTH PROBES REMOVED (Fixes the 0/1 READY issue)
        # -----------------------------------------------------------------
